sudo: false
dist: trusty
language: ruby

notifications:
  email: false

before_install:
  - unset _JAVA_OPTIONS

matrix:
  include:
    - rvm: 2.2.10
    - rvm: 2.3.7
    - rvm: 2.4.4
    - rvm: 2.5.1
    - rvm: jruby-9.1.17.0
      env: JRUBY_OPTS="--dev"
