sudo: false
dist: trusty
language: ruby

notifications:
  email: false

before_install:
  - unset _JAVA_OPTIONS

matrix:
  include:
    - rvm: 2.1.10
    - rvm: 2.2.7
    - rvm: 2.3.4
    - rmv: 2.4.1
    - rvm: jruby-9.1.9.0
      env: JRUBY_OPTS="--dev"
